# Generated by Django 5.2.17 on 2026-09-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('analyzed', 'Analyzed'), ('failed', 'Failed'), ('uploaded', 'Uploaded')], default='uploaded', max_length=20),
        ),
    ]
