# Generated by Django 5.2.17 on 2026-09-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_resume_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeanalysis',
            options={'verbose_name_plural': 'resume analyses'},
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='detected_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='improvements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='job_relevance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='notice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='provider',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='recommended_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='skill_gaps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
