# Generated by Django 5.2.17 on 2026-09-26 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
        ('jobs', '0002_rename_expires_at_job_application_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewturn',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='last_error',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='mode',
            field=models.CharField(choices=[('voice', 'Voice'), ('text', 'Text')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='report_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='state',
            field=models.CharField(choices=[('preparing', 'Preparing interview'), ('ai_speaking', 'AI is speaking'), ('awaiting_answer', 'Your turn'), ('listening', 'Listening'), ('processing', 'Processing answer'), ('evaluating', 'AI is evaluating'), ('completed', 'Interview completed')], default='preparing', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewturn',
            name='category',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='interviewturn',
            name='client_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='interviewturn',
            name='evaluation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='interviewturn',
            name='source',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('aborted', 'Aborted')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewturn',
            name='kind',
            field=models.CharField(choices=[('question', 'Question'), ('answer', 'Answer'), ('evaluation', 'Evaluation')], default='question', max_length=20),
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['student', 'status'], name='interviews__student_cea321_idx'),
        ),
        migrations.AddConstraint(
            model_name='interviewturn',
            constraint=models.UniqueConstraint(condition=models.Q(('client_token', ''), _negated=True), fields=('session', 'client_token'), name='unique_interview_answer_client_token'),
        ),
    ]
