# Generated by Django 5.2.17 on 2026-09-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='college',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
