# Generated by Django 5.2.17 on 2026-09-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_technologies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='student_profiles', to='jobs.skill'),
        ),
    ]
