# Generated by Django 5.2.17 on 2026-09-26 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_bio_studentprofile_degree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_emails_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'super admin email',
                'verbose_name_plural': 'super admin emails',
                'ordering': ['-created_at'],
            },
        ),
    ]
