# Generated by Django 5.2.17 on 2026-09-24 13:40

import django.db.models.deletion
from django.db import migrations, models


def remap_categories(apps, schema_editor):
    """Move legacy 'technical' quizzes onto the granular category values."""
    Quiz = apps.get_model("assessments", "Quiz")
    for quiz in Quiz.objects.filter(category="technical"):
        hay = f"{quiz.title} {quiz.description}".lower()
        if "django" in hay or "rest" in hay or "web" in hay:
            quiz.category = "django"
        else:
            quiz.category = "python"
        quiz.save(update_fields=["category"])


def backfill_attempts(apps, schema_editor):
    """Backfill attempt status/incorrect_count and per-question answer rows."""
    QuizAttempt = apps.get_model("assessments", "QuizAttempt")
    QuizQuestionAnswer = apps.get_model("assessments", "QuizQuestionAnswer")
    for attempt in QuizAttempt.objects.all():
        if attempt.submitted_at is not None:
            attempt.status = "completed"
        attempt.incorrect_count = max(0, attempt.total - attempt.correct_count)
        attempt.save(update_fields=["status", "incorrect_count"])

    existing = set(
        QuizQuestionAnswer.objects.values_list("attempt_id", "question_id")
    )
    for attempt in QuizAttempt.objects.filter(status="completed"):
        answers = attempt.answers or {}
        q_map = {
            q["id"]: q["correct_index"]
            for q in attempt.quiz.questions.values("id", "correct_index")
        }
        for raw_qid, raw_chosen in answers.items():
            try:
                qid = int(raw_qid)
            except (TypeError, ValueError):
                continue
            if (attempt.pk, qid) in existing or qid not in q_map:
                continue
            try:
                chosen = int(raw_chosen)
            except (TypeError, ValueError):
                chosen = None
            QuizQuestionAnswer.objects.create(
                attempt_id=attempt.pk,
                question_id=qid,
                chosen_index=chosen,
                is_correct=chosen is not None and chosen == q_map[qid],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='incorrect_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('django', 'Django'), ('sql', 'SQL'), ('dbms', 'DBMS'), ('operating_systems', 'Operating Systems'), ('computer_networks', 'Computer Networks'), ('data_structures', 'Data Structures'), ('aptitude', 'Aptitude'), ('logical_reasoning', 'Logical Reasoning')], default='python', max_length=30),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for no time limit.', null=True),
        ),
        migrations.CreateModel(
            name='QuizQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='assessments.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='assessments.question')),
            ],
            options={
                'ordering': ['question_id'],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_question_answer')],
            },
        ),
        migrations.RunPython(remap_categories, migrations.RunPython.noop),
        migrations.RunPython(backfill_attempts, migrations.RunPython.noop),
    ]
