# Generated by Django 5.2.17 on 2026-09-24

import django.db.models.deletion
from django.db import migrations, models


def backfill_required_skills(apps, schema_editor):
    """Copy legacy JSON ``skills_required`` into the new M2M relationship."""
    Job = apps.get_model("jobs", "Job")
    Skill = apps.get_model("jobs", "Skill")

    def names(value):
        if isinstance(value, str):
            return [value]
        if not isinstance(value, (list, tuple)):
            return []
        return [str(v) for v in value if str(v).strip()]

    for job in Job.objects.all():
        raw = None
        try:
            raw = job.skills_required
        except AttributeError:
            pass
        if not raw:
            continue
        for name in names(raw):
            skill, _ = Skill.objects.get_or_create(name=name.strip())
            job.required_skills.add(skill)


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '0002_alter_resume_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='expires_at',
            new_name='application_deadline',
        ),
        migrations.AddField(
            model_name='job',
            name='education_required',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='job',
            name='min_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='preferred_skills',
            field=models.ManyToManyField(blank=True, related_name='jobs_preferred', to='jobs.skill'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='jobs_required', to='jobs.skill'),
        ),
        migrations.RunPython(backfill_required_skills, migrations.RunPython.noop),
        migrations.AddField(
            model_name='jobapplication',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='resumes.resume'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills_required',
        ),
    ]